feat: add husky config

diff --git a/frontend/.husky/pre-push b/frontend/.husky/pre-push
--- a/frontend/.husky/pre-push
+++ b/frontend/.husky/pre-push
@@ -1,4 +1,11 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm test
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to the master branch"
+  exit 1
+fi
+
+npm run test
